### ISSUE TITLE
Inventory models coordination

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/ietf-network-inventory#26]
**[2021-11-17 Network Inventory call](https://github.com/italobusi/ietf-network-inventory/blob/main/minutes/minutes-2021-11-17.md)**

During IETF 112 OPSAWG meeting, the issue of disambiguating the concept of inventory has been raised:

https://notes.ietf.org/notes-ietf-112-opsawg

A dedicated OPSAWG interim meeting may be scheduled.

**Comment by italobusi** [comment]
**2021-11-24 Network Inventory call**

Related work on "inventory" within OPSAWG:
* https://datatracker.ietf.org/doc/draft-palmero-opsawg-dmlmo/
* https://datatracker.ietf.org/doc/draft-claise-opsawg-collected-data-manifest/
* https://datatracker.ietf.org/doc/draft-ietf-opsawg-sbom-access/
* https://datatracker.ietf.org/doc/draft-yg3bp-ccamp-optical-inventory-yang/
* https://datatracker.ietf.org/doc/draft-dbwb-opsawg-sap/

- [ ] Review the drafts and be prepared for OPSAWG discussion

**Comment by YuChaode** [comment]
draft-palmero-opsawg-dmlmo-02：
this draft introduces a lifecycle management and operation(LMO) solution. It focus on the LMO data which includes but not limited to asset inventory, licenses information, feature usage and incident management. Our draft may have some overlap with its asset inventory concept. According to the asset inventory model defined in this draft, it seems their inventory management is in large granularity. The asset types include hw, sw, sw-cloud, phone and other. And it also defines a sub-asset id list underlay the asset root, the subasset id points to asset id. This idea  more or less looks like our generic modeling idea. And for sub-asset types, they include router, switch, wireless, controller, board, power-supply, transceiver and others.

draft-claise-opsawg-collected-data-manifest-00:
This draft sounds like serving for telemetry and if you read it a little bit deeply, you will find it cannot be used for inventory management. It can be a part of inventory information but not all. According to the abstract of this draft, the author point out the existing issue of model-driven telemetry for missing contextual information. The contextual information includes identifying what kinks of data produced by device and how should the client collect this data from device. The author call them platform manifest and collection manifest. I think we could consider the platform manifest for device as yang-lib for controller. 

draft-ietf-opsawg-sbom-access-03:
This draft introduce a module to discover the software running on the device and retrieve known vulnerabilities for this software. I thin this draft cannot fully replace our inventory draft. But the software and vulnerabilities can be a part of information, just like the collected-data-manifest model.

draft-yg3bp-ccamp-optical-inventory-yang:
This is the draft we are proposing.

draft-dbwb-opsawg-sap-00: 
This draft introduce a new concept of SAP (service attach point) in network model. And the author considers it can be the inventory model mentioned in RFC8345. I don't agree with this idea. IMHO, the SAP is still related with service or connection configuration which can also be covered by termination point of abstract network model. If the author consider that there is a requirement of identifying what kinds of service can be supported by the port, it is better to augment some more attributes in TP, just like we augments client-facing and supporting-client-signals in OTN topology. And the model they propose in this draft, they provide a new network type, SAP network, and a SAP list underlay the node root. It cannot cover the management of rack, shelf, slot as we recognized. That is the reason why i don't agree that this SAP network is the inventory model.

**Comment by italobusi** [comment]
2021-12-17 Network Inventory call

**draft-palmero-opsawg-dmlmo-02**：here there is some overlapping with our draft. "Asset" in this draft should have the same meaning of our "component". It considers Hw assett so it is close to our draft.

**draft-claise-opsawg-collected-data-manifest-00**: inventory of yang models capabilities of device

**draft-ietf-opsawg-sbom-access-03**: different type of inventory, just SW inventory.

**draft-dbwb-opsawg-sap-**00:
Anton: the draft is trying to find UNI ports in the netwrok and the service capable ports. Not inventory. IP service capable ports.
To expose an abstracted view of a very simple of connectivity matrix. Just edge ports.
Italo: it is an inventory of topological element.
Anton: which ports are service capable, e.g. I can setup L2 or L3 VPN service on these ports.
No contention at alla with respect our draft.
Is is very IP oriented draft.

Regarding again the first draft:

Italo/Aihua: need to qualify the term inventory, HW inventory, or topology inventory or other.

Jeff: we need to clarify that we are focusing on hardware network inventory. Our objective is simpler than what is in this draft. Even if there is some overlap, our scope is a bit clear.

Anton: we have a subset of what it is happening

Italo: if it is a subset, a profile can still be used so this model can be modularized to allow using only the asset or augmenting the definition of the asset inventory

Anton: another solution is to put our inventory model within the draft. May need to check what is the difference between our data model and their asset data model

Italo: it seems that the structure is already modular, section 6.1.1 defines an asset inventory model which can be used as a stand-alone model and it might support our needs. We need to review the YANG model in 6.1.1 in more details.

Aihua: we should compare this module with our model and see if we can extract the common parts

Italo: not sure if the model applies to device and/or controllers but it looks like quite generic and applicable on multiple scenarios (including controller's NBI)

Anton: it seems applicable to any scenario where you have different applications, servers, ... and you want to manage them in the same controller. Our model was meant to be more specific for a transport/provider network environment. This model may probably lack some specificities we need in our environment

- [ ] **All**: review the ietf-lmo-assets-inventory model and compare with our proposed model
- [ ] Italo: clarify with the other people in OPSAWG that our draft is dealing with network hardware inventory and potentially overlaps with the ietf-lmo-assets-inventory model

**Comment by italobusi** [comment]
The scope has been clarified to be the network hardware inventory

**Comment by italobusi** [comment]
**[2022-11-16 Network Inventory call](https://github.com/italobusi/ietf-network-inventory/blob/main/minutes/minutes-2022-11-16.md)**

Issue #26 has been re-opened to track the inventory models coordination started during IETF 115

The feedback from IETF115 and the side meeting
- Robert Wilton agreed that it’s a good idea to compare openconfig and our data model, and he suggested we could compare  the structure of these two model and we could have different terminologies.
- According to the side meeting, a new mailing list will be set up to coordinate different inventory drafts.

The material presented at the meeting is available at: https://github.com/billwuqin/Inventory-management-using-YANG

The Inventory YANG mailing list has been already setup:

https://www.ietf.org/mailman/listinfo/Inventory-yang

It is not yet clear whether we are going to be subscribed automatically or we should subscribe by our own. A question has been sent to the list administrator.

- [ ] @italobusi provide feedbacks about the need to subscribe to the Inventory YANG mailing list

All the contributors to this draft are invited to join this list and actively contribute to the discussion

Our current view is that there is no overlapping between the scope of our draft, which is a network model for hardware inventory, and the scope of other drafts submitted to OPSAWG

As soon as the list is operational, we can share with the other participants the result of the analysis we have already done: https://github.com/italobusi/ietf-network-inventory/issues/26#issuecomment-996907583

This analysis is not covering [draft-wzwb-opsawg-network-inventory-management-00](https://datatracker.ietf.org/doc/html/draft-wzwb-opsawg-network-inventory-management), which has been recently submitted

- [ ] Review [draft-wzwb-opsawg-network-inventory-management-00](https://datatracker.ietf.org/doc/html/draft-wzwb-opsawg-network-inventory-management) to identify any potential overlapping with our draft

**Comment by italobusi** [comment]
**[2022-11-23 Network Inventory weekly call
](https://github.com/italobusi/ietf-network-inventory/blob/main/minutes/minutes-2022-11-23.md)**

Sergio: I don’t see any overlap with the other draft, but i concern that these argument will delay our work.

Jeff: I will send an email to the mailing list to tell that, from our operators perspective, the inventory data model we are working on is the inventory data we want and there is no overlap with the other drafts.

**Comment by italobusi** [comment]
**[2023-05-24 Network Inventory weekly call](https://github.com/italobusi/ietf-network-inventory/blob/main/minutes/minutes-2023-05-24.md)**

Reviewed the latest version of proposed charter: https://mailarchive.ietf.org/arch/msg/inventory-yang/GcBEYEnG07JZHL1mPTT994N8B6I/

Comments:
- D: multi-layer is not a proper name for inventory objects. Better to use the term layer-independent or layer-agnostic for inventory
- E: correlation might be understood as implying some complex processing, better to use relationship instead

- [ ] @nigel-r-davis raise the comment on the Inventory mailing list

There is a lot of potential complexity when dealing with planning of components and may be worthwhile understanding what should be covered by the inventory model

Jeff/Fabio: at least it could be important to mark an holder as reserved (e.g., because a new board is planned to be deployed there)

Issue #82 created to track the discussion on this topic

**Comment by italobusi** [comment]
The IVY WG has been formed and a session is planning at IETF 117

Proposal from the chairs:

> If you’ve already proposed a network inventory related document:
> - Send a mail to this mailing list saying " Hey, I/we wrote a draft related to inventory, here it is". This will allow people getting a better awareness of all the material already present and spread in different WGs.
> - Identify which parts of your existing drafts would fit into the core model.
> - Book a slot at IETF 117 to discuss about it, there will be room for everyone.

My suggestion is:
- me to send a mail to the IVY mailing list notifying our draft and request a presentation slot at IETF 117
- work together on identifying which parts of your existing drafts would fit into the core model

**Comment by italobusi** [comment]
Closed by the new [IVY WG](https://datatracker.ietf.org/wg/ivy/about/)
