### ISSUE TITLE
Need to find TMF reference for the equipment document SD2-20_EquipmentModel.pdf

### ISSUE THREAD

**Issue by sergiobelotti** [ietf-ccamp-wg/ietf-network-inventory#39]
In our Inventory model we use as reference TMF document related to Equipment model but we have no official TMF reference to use in the draft in the References section.

**Comment by sergiobelotti** [comment]
The official TMF reference for Equipment Model document is:
https://www.tmforum.org/resources/standard/resource-management-operations-related-dm-ddps-networkresourcefulfilment-nrf-2/
To whom have a TMF account: you need to download the zip file from this link, the document is in the SD directory.

**Comment by sergiobelotti** [comment]
> The official TMF reference for Equipment Model document is: https://www.tmforum.org/resources/standard/resource-management-operations-related-dm-ddps-networkresourcefulfilment-nrf-2/ To whom have a TMF account: you need to download the zip file from this link, the document is in the SD directory.

The better thing is to reference our document as part of TMF MTOSI 4.0, NetworkResourceFullfillment package
https://www.tmforum.org/resources/suite/mtosi-4-0/

**Comment by italobusi** [comment]
> This is the proposal to reference the TMF document in our draft ,Italo and myself are thinking to adopt after check with TMF expert: [TMF_SD2-20] TM Forum, "SD2-20_Equipment Model", TMF MTOSI 4.0, Network Resource Fulfilment (NRF), SD2-20, May 2008, < [https://www.tmforum.org/resources/suite/mtosi-4-0>](https://www.tmforum.org/resources/suite/mtosi-4-0%3E)

[2022-04-27 Network Inventory weekly call
](https://github.com/italobusi/ietf-network-inventory/blob/main/minutes/minutes-2022-04-27.md)

Proposal agreed

- [ ] @italobusi : update the draft with this new reference

**Comment by italobusi** [comment]
Closed with https://datatracker.ietf.org/doc/html/draft-yg3bp-ccamp-network-inventory-yang-02

**Comment by italobusi** [comment]
Re-opened since the reference in the draft is not the same as the one agreed in https://github.com/italobusi/ietf-network-inventory/issues/39#issuecomment-1105187790
