### ISSUE TITLE
Bo WG adoption call comments

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/ietf-network-inventory#60]
> 1) This draft title is ‘A YANG Data Model for Optical Network Inventory’, but the YANG module name is “ietf-network-inventory”.  Is it better to be consistent to be named as “ietf-optical-network-inventory”?
> 
> 2) The draft states RFC 8345 recommends that network inventory should be augmentation to “ietf-network”, but there is no analysis on this. Can you add some description to this?
> 
> 3) “equipment-room” definition is related to specific implementation. Could you change it to “site”?  For example, some enterprise networks can be distributed in different geographical areas, not limited to several equipment rooms. Generally, multiple racks are aggregated by “site”.
> 
> 4) The model is limited to hardware inventory. Why is software not included in the optical network inventory?
> 

See: https://mailarchive.ietf.org/arch/msg/ccamp/kwtJgFWlgNBVInLOszj4c4PVsdo/

**Comment by italobusi** [comment]
**[2023-01-11 Network Inventory weekly call
](https://github.com/italobusi/ietf-network-inventory/blob/main/minutes/minutes-2023-01-11.md)**

> 1) This draft title is ‘A YANG Data Model for Optical Network Inventory’, but the YANG module name is “ietf-network-inventory”.  Is it better to be consistent to be named as “ietf-optical-network-inventory”?
> 

This issue has been already clarified by Chaode and Bo on the CCAMP WG mailing list: this draft is addressing network hardware inventory for Optical, IP and MW networks.

> 4) The model is limited to hardware inventory. Why is software not included in the optical network inventory?
> 

In IP network there is also the need for software inventory as well as virtual (NFV-based) components

Jeff: this is needed for virtual CPE and virtual BNG but for IP routers this is not needed

Bo: but virtual CPE actually is a router

Jeff/Fabio: the focus of this draft is the actual router and not the virtual components since there is no IETF standard YANG model for IP router inventory

Italo: maybe we can keep the virtual components outside the scope of our work but check that the model can be extended to support them in the future

This issue requires further investigation: issue #64 has been added to track this issue

**Comment by italobusi** [comment]
**[2023-02-15 Network Inventory weekly call](https://github.com/italobusi/ietf-network-inventory/blob/main/minutes/minutes-2023-02-15.md)**

> The draft states RFC 8345 recommends that network inventory should be augmentation to “ietf-network”, but there is no analysis on this. Can you add some description to this?
> 

Past discussion tracked in issue #14

There is a typo in the conclusion: the group has agreed NOT to augment RFC8345

It may worthwhile to add some text in the document to clarify the rationale for this choice

Agreed to re-open issue #14 to track this discussion

**Comment by italobusi** [comment]
**[2023-02-22 Network Inventory weekly call](https://github.com/italobusi/ietf-network-inventory/blob/main/minutes/minutes-2023-02-22.md)**

> 3) “equipment-room” definition is related to specific implementation. Could you change it to “site”?  For example, some enterprise networks can be distributed in different geographical areas, not limited to several equipment rooms. Generally, multiple racks are aggregated by “site”.
> 

Site is more generic:
- not all devices are located in rack (stand-alone devices)
- not all devices are located in a room (outdoor devices)
- not all devices have fixed location (mobile devices)

It is possible to generalize the model as:

```
     +--ro sites
     |  +--ro site* [uuid]
     |     +--ro uuid           yang:uuid
     |     ...
     |     +--ro site-location? string
     |     +--ro geo-location
     |     |   ...
     |     +--ro racks        // 0 or more racks
     |     |  +--ro rack* [uuid]
     |     |     +--ro uuid                 yang:uuid
     |     |     ...
     |     |     +--ro rack-location    // optional if not in an equipment-room
     |     |     |  +--ro equipment-room-name?   leafref
     |     |     |  +--ro row-number?            uint32
     |     |     |  +--ro column-number?         uint32
     |     |     ...
     |     |     +--ro contained-chassis* [ne-ref component-ref]
     |     |        +--ro ne-ref           leafref
     |     |        +--ro component-ref    leafref
     |     +--ro stand-alone-devices        // 0 or more stand-alone devices
     |        ...
```

In the context of a telecom network, the site always corresponds to an equipment-room

Need more time to double check whether this approach would be generic enough to cover all the use cases

We can further review and discuss this option in the next call(s)

**Comment by YuChaode** [comment]
can we define both site and equipment-room in the data model as this proposal?
[site and equipment-room modeling.pptx](https://github.com/ietf-ccamp-wg/ietf-network-inventory/files/10909216/site.and.equipment-room.modeling.pptx)

**Comment by italobusi** [comment]
**[2023-04-19 Network Inventory weekly call](https://github.com/italobusi/ietf-network-inventory/blob/main/minutes/minutes-2023-04-19.md)**

It has also been discussed the possibility to add a list of site and to structure it in a recursive manner (such as a site can contain other sites)

For example, a campus can be a site which contains buildings and a building can be another site which contains equipment rooms, and so on

**Comment by italobusi** [comment]
@lana-wu: Check if the issue can be closed with [draft-y3bp-ivy-network-inventory-yang](https://datatracker.ietf.org/doc/html/draft-y3bp-ivy-network-inventory-yang) and [draft-wzwb-ivy-network-inventory-software](https://datatracker.ietf.org/doc/html/draft-wzwb-ivy-network-inventory-software).
