### ISSUE TITLE
Management of NEs with multiple racks

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/ietf-network-inventory#7]
Evaluate whether there is a requirement to manage NEs composed by multiple racks and how to manage them.

**Comment by italobusi** [comment]
Possible solution using the approach in #2 (assuming that no rack and no shelf is defined for the top-level component):

![image](https://user-images.githubusercontent.com/12461741/130317112-f4f054d7-8718-40b8-aeb9-5ac1ba0bfd0d.png)

Co-authored-by: agva123 agva123@gmail.com

**Comment by italobusi** [comment]
**[2023-02-15 Network Inventory weekly call](https://github.com/italobusi/ietf-network-inventory/blob/main/minutes/minutes-2023-02-15.md)**

- [ ] @italobusi @YuChaode Check whether these examples are already covered with the examples in #55

**Comment by sergiobelotti** [comment]
> Slides updated based on the discussion on 2023-04-26: [multi-rack-NE-questions-01.pptx](https://github.com/ietf-ccamp-wg/ietf-network-inventory/files/11422095/multi-rack-NE-questions-01.pptx)
> 
> * slide 2 updated with the option to indicate r=1 as the rack location
> * slide 3 added with possible changes to the model to address the comments discussed during the call

@italobusi What is the meaning of green value (e.g. in slide 3 r=2 ) vs. the red one (e.g. same slide 3 rack 1-1) ? thanks.

**Comment by italobusi** [comment]
> @italobusi What is the meaning of green value (e.g. in slide 3 r=2 ) vs. the red one (e.g. same slide 3 rack 1-1) ? thanks.

I am struggling with the terminology to properly describe the legenda

The green values are the "component location" within the network-element (following the r/sh/slot/port string pattern while the red values are the "relative position" of e.g., the rack within the room (row and column) or the shelf within the rack (as shown in the slides presented at IETF 116)

**Comment by sergiobelotti** [comment]
> > @italobusi What is the meaning of green value (e.g. in slide 3 r=2 ) vs. the red one (e.g. same slide 3 rack 1-1) ? thanks.
> 
> I am struggling with the terminology to properly describe the legenda
> 
> The green values are the "component location" within the network-element (following the r/sh/slot/port string pattern while the red values are the "relative position" of e.g., the rack within the room (row and column) or the shelf within the rack (as shown in the slides presented at IETF 116)

@italobusi I see your problem ! but your clarification is completely fine with me. Maybe saying green --> component location (e.g. within Network Element) , red --> relative position (with respect parent component e.g. rack for shelf,, equipment room for rack )

**Comment by italobusi** [comment]
**[2023-05-10 Network Inventory weekly call](https://github.com/italobusi/ietf-network-inventory/blob/main/minutes/minutes-2023-05-10.md)**

Slides reviewed and updated during the discussion: [multi-rack-NE-questions-02](https://github.com/ietf-ccamp-wg/ietf-network-inventory/files/11451239/multi-rack-NE-questions-02.pptx)

The detailed changes to the model needs further discussion pending confirmation of the requirements to be addressed

- [ ] **Italo**: check with the operators if there are requirements to manage cases where the rack belongs to the NE and where the shelf does not belong to the NE

**Comment by italobusi** [comment]
**[2023-05-24 Network Inventory weekly call](https://github.com/italobusi/ietf-network-inventory/blob/main/minutes/minutes-2023-05-24.md)**

> [x] **Italo**: check with the operators if there are requirements to manage cases where the rack belongs to the NE and where the shelf does not belong to the NE

Jeff: for me the rack is not part of the NE but the NE can be spread over multiple racks

Nigel: I have see a variety of equipment types

The difference between the left and right figures in slide 2 of [multi-rack-NE-questions-02](https://github.com/ietf-ccamp-wg/ietf-network-inventory/files/11451239/multi-rack-NE-questions-02.pptx) is that in the right figure the NE owns the rack and it is aware of the rack while on the left figure the NE is not aware of the fact that its shelves are located on the same rack

Fabio: in the cases where the rack belongs to the NE, the rack contains only one shelf and not multiple shelves

Nigel: better not to restrict the model and define a list which can have only one element

Phil: sometimes in a multi-chassis system there is a logical rack identifier which is arbitrary and not related with the physical rack location

As a consequence the "r=1" string in the location string does not necessarily mean that the rack belongs to the NE but it may mean that the shelf is associated with a logical rack. This 'rack' actually correspond with the component ```stack``` in RFC8348 which can be either a physical or a logical grouping of chassis.

**Conclusion**: no need to have an association between the rack physical element and the stack NE component of a network-element. The association can still be kept between the shelf physical element and the chassis NE component as in the current model.

Slides updated based on the feedbacks of this call: [multi-rack-NE-questions-03.pptx](https://github.com/ietf-ccamp-wg/ietf-network-inventory/files/11568147/multi-rack-NE-questions-03.pptx)

Need to further discuss:
- the case of a single-board NE (when the chassis does not belong a a NE)
- the case of a pizza box which may or may not be located on a rack

**Comment by YuChaode** [comment]
2023-06-28 weekly call:
