### ISSUE TITLE
Relationship with ietf-topology

### ISSUE THREAD

**Issue by oscargdd** [ietf-ccamp-wg/ietf-network-inventory#75]
SDN controllers will likely report the network topology using ietf-topology data models. The draft should define how the inventory and network models are linked. 

One choice is to provide an augmentation for the IETF-network to add a leafreaf to an inventory node and provide an example.  Alternatively, you can do the other way around, in the inventory include an optional leafer to a topology node. 

The nodes might have different names so we should not infer that node-id is the key to join both.

**Comment by oscargdd** [comment]
I saw you just included those :-)

**Comment by italobusi** [comment]
Duplicate with #14
